SELECT 
    D.NOM_DISC AS 'Nome da Disciplina'
FROM
    DISCIPLINAS D
        JOIN
    TURMAS T ON D.COD_DISC = T.COD_DISC
        JOIN
    HISTORICOS H ON T.SEMESTRE = H.SEMESTRE
GROUP BY D.NOM_DISC
HAVING SUM(CASE
    WHEN H.SITUACAO = 'RF' THEN 1
    ELSE 0
END) >= 0.5 * COUNT(H.MAT_ALU);