CREATE TABLE IF NOT EXISTS CHAVETA(
    CHAVE VARCHAR(30),
    DESCRICAO VARCHAR(60),
    VALOR VARCHAR(200),
    PRIMARY KEY(CHAVE)
);

INSERT INTO CHAVETA (CHAVE, DESCRICAO, VALOR) VALUES ('ANO ATU', 'Ano Atual', 2011);
INSERT INTO CHAVETA (CHAVE, DESCRICAO, VALOR) VALUES ('SEM_ATU', 'Semestre atual', 1);
INSERT INTO CHAVETA (CHAVE, DESCRICAO, VALOR) VALUES ('NOM EMP', 'Nome da instituição', 'Universidade Tiradentes');
INSERT INTO CHAVETA (CHAVE, DESCRICAO, VALOR) VALUES ('DAT_VEST', 'Data do vestibular', '03/11/2011');