SELECT 
    P.NOM_PROF AS 'Nome do Professor'
FROM 
    PROFESSORES P
JOIN 
    TURMAS T ON P.IDT_PROF = T.IDT_PROF
JOIN 
    HISTORICOS H ON T.SEMESTRE = H.SEMESTRE
GROUP BY 
    P.IDT_PROF, P.NOM_PROF
HAVING 
    SUM(CASE WHEN H.SITUACAO = 'RF' THEN 1 ELSE 0 END) >= 0.6 * COUNT(H.MAT_ALU)