SELECT 
    D.COD_DISC AS 'Código',
    D.NOM_DISC AS 'Nome Disciplina',
    D.CREDITOS AS 'Créditos'
FROM
    DISCIPLINAS D
LEFT JOIN
    HISTORICOS H ON D.COD_DISC = H.COD_DISC
WHERE
    D.CREDITOS = 6
    AND D.HORAS_OBRIG < 4
    AND H.COD_DISC IS NULL;
