SELECT 
    COUNT(DISTINCT T.COD_DISC) AS 'Total de Turmas Completas'
FROM
    TURMAS T
        JOIN
    MATRICULAS M ON T.ANO = M.ANO
        AND T.SEMESTRE = M.SEMESTRE
        AND T.COD_DISC = M.COD_DISC
WHERE
    T.ANO = 2011 AND T.SEMESTRE = 3
GROUP BY T.COD_DISC , T.VAGAS
HAVING COUNT(M.MAT_ALU) = T.VAGAS