SELECT 
    D.COD_DISC AS 'Código', D.NOM_DISC AS 'Nome Disciplina'
FROM
    DISCIPLINAS D
        JOIN
    MATRIZES M ON D.COD_DISC = M.COD_DISC
GROUP BY D.COD_DISC , D.NOM_DISC
HAVING COUNT(M.COD_DISC) > 1