SELECT 
    D.COD_DISC AS 'Código',
    D.NOM_DISC AS 'Nome Disciplina',
    D.CREDITOS AS 'Créditos'
FROM
    DISCIPLINAS D
LEFT JOIN
    MATRICULAS M ON D.COD_DISC = M.COD_DISC
WHERE
    D.CREDITOS = 6
    AND M.COD_DISC IS NULL
